version: '3.8'
services:
  auth-postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - auth-postgres:/var/lib/postgresql/data
  
  auth-redis-db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - auth-redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
networks:
  auth-network:
    driver: bridge

volumes:
  auth-postgres:
  auth-redis: